---
build_from:
  amd64: 'ghcr.io/hassio-addons/base/amd64:10.2.0'
  armhf: 'ghcr.io/hassio-addons/base/armhf:10.2.0'
  armv7: 'ghcr.io/hassio-addons/base/armv7:10.2.0'
  aarch64: 'ghcr.io/hassio-addons/base/aarch64:10.2.0'
